#!/usr/bin/env bash
# Create a login for a site the agent is signing up to, with a generated password.
#
# The password is generated by 1Password server-side (`generate: true` plus a
# recipe) rather than by the agent. That keeps password strength off the model's
# judgement, and the plaintext exists in the vault before it is ever shown.
#
# Usage: create.sh <domain> <username-or-email> [options]
#   --url <url>      site URL to store (default: https://<domain>)
#   --title <title>  item title (default: <domain>)
#   --length <n>     password length (default 32)
#   --no-symbols     letters and digits only, for sites that reject symbols
#   --force          create even if an account for this domain already exists
#   --reveal         print the generated password (see below before using)
#
# The password is NOT printed by default. Everything this prints goes into the
# terminal transcript and the gateway logs, and a password there outlives the
# task by however long those are kept — so disclosure is a deliberate act, not
# the default. The account is fully usable without ever revealing it: pipe it
# straight where it is needed with
#   1pass-read/scripts/show.sh <domain> password --exec <command>
# and reach for --reveal only when the model itself has to type it into a form.

set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

[[ $# -ge 2 ]] || die "usage: create.sh <domain> <username-or-email> [options]"
domain=$1 username=$2; shift 2

url="" title="" length=32 symbols=true reveal=false force=false
while [[ $# -gt 0 ]]; do
  case $1 in
    --url)        url=${2:?--url needs a value}; shift 2 ;;
    --title)      title=${2:?--title needs a value}; shift 2 ;;
    --length)     length=${2:?--length needs a value}; shift 2 ;;
    --no-symbols) symbols=false; shift ;;
    --reveal)     reveal=true; shift ;;
    --force)      force=true; shift ;;
    # Accepted and ignored: not printing is now the default, and failing here
    # would break callers written against the earlier behaviour.
    --quiet)      shift ;;
    *)            die "unknown option: $1" ;;
  esac
done

[[ $length =~ ^[0-9]+$ ]] || die "--length must be a number"
: "${url:=https://${domain}}"
: "${title:=${domain}}"

vault=$(resolve_vault)

if [[ $force == false ]]; then
  existing=$(find_items "$vault" "$domain")
  if [[ $(jq 'length' <<<"$existing") -gt 0 ]]; then
    die "an account for '${domain}' already exists:
$(jq -r '.[] | "  \(.id)  \(.title)"' <<<"$existing")
Use --force to add a second one, or set-field.sh to update the existing item."
  fi
fi

charsets='["LETTERS","DIGITS","SYMBOLS"]'
[[ $symbols == true ]] || charsets='["LETTERS","DIGITS"]'

body=$(jq -n \
  --arg vault "$vault" --arg title "$title" --arg username "$username" \
  --arg url "$url" --argjson length "$length" --argjson charsets "$charsets" '{
    vault: { id: $vault },
    title: $title,
    category: "LOGIN",
    urls: [ { href: $url, primary: true } ],
    fields: [
      { id: "username", purpose: "USERNAME", type: "STRING",    value: $username },
      { id: "password", purpose: "PASSWORD", type: "CONCEALED",
        generate: true, recipe: { length: $length, characterSets: $charsets } }
    ]
  }')

created=$(connect POST "/v1/vaults/${vault}/items" "$body") \
  || die "create failed — run preflight.sh to check this token can write"

item_id=$(jq -r '.id' <<<"$created")
password=$(field_of PASSWORD "$created")

[[ -n $password ]] || die "item ${item_id} was created but returned no password — inspect it before reusing"

echo "Created '${title}' (${item_id}) in the vault."
echo "  username: ${username}"
if [[ $reveal == true ]]; then
  echo "  password: ${password}"
  echo
  echo "That password is now in the transcript. Use it, then do not repeat it."
else
  vault_name=$(connect GET /v1/vaults | jq -r --arg v "$vault" '.[] | select(.id == $v) | .name')
  echo "  password: stored, ${#password} chars, not shown"
  echo
  echo "To use it without putting it in the transcript, read it into a variable:"
  echo "  PASSWORD=\$(op read \"op://${vault_name}/${title}/password\")"
  echo "Only if the model itself must type it: create.sh ... --reveal"
fi
echo
echo "Next: if the site offers 2FA, enable it and store the seed with"
echo "  set-totp.sh ${item_id} '<otpauth-uri-or-secret>'"
echo "then save the recovery codes it shows on the same screen with"
echo "  set-recovery.sh ${item_id}      # codes on stdin, one per line"
